### ISSUE TITLE
Can not understand "stdp_triplet_all_in_one_synapse" clearly

### ISSUE THREAD

**Issue by xiaoxiaoluzl** [zifeo/NEST-STDPModule#4]
Hi:
  I have troubles in understanding the  "stdp_triplet_all_in_one_synapse".Does triplets in STDP model mean three spikes from only two neurons,or more neurons?

**Comment by seeholza** [comment]
Triplets refer to pairings of 3 spikes from both pre and postsynaptic neurons. Please check the publication that proposed the learning rule here: https://www.ncbi.nlm.nih.gov/pubmed/16988038

Also, scholarpedia has a section on this here http://www.scholarpedia.org/article/Spike-timing_dependent_plasticity#Triplet_rule_of_STDP

**Comment by xiaoxiaoluzl** [comment]
Thanks for answering my question, and I have read the article "Triplets of Spikes in a Model of Spike Timing-Dependent Plasticity" before. But I can not understand how triplets in STDP mode apply to the Triplet protocol or Quadruplet protocol.

**Comment by seeholza** [comment]
"Triplets" just relate to several (three) spikes of pre- and postsynaptic neurons coinciding in a short time window (as in here http://www.scholarpedia.org/w/images/thumb/0/05/STDP-Fig5.png/800px-STDP-Fig5.png, where you see a post-pre-post triplet). These are different from usual two-spike-pairings of only pre-post or post-pre "doublets".

In the STDP model (also in the one in the NEST main repository https://github.com/nest/nest-simulator/blob/master/models/stdp_triplet_connection.h), this is implemented by synaptic traces of on longer timescales, and their combination in the weight update rule (dw(t)/dt).

**Comment by xiaoxiaoluzl** [comment]
Thanks for your answers, so if I want to test the triplets using the Quadruplet protocol, I just have to modify the stimulating time which will contsist of 60 quadruplets? And another question,according to the aiticle "Triplets of Spikes in a Model of Spike Timing-Dependent Plasticity"
http://www.jneurosci.org/content/26/38/9673
,if  I want to see the LTP,there wii be two post and one pre? or see the LTD, there will be two pre and one post?  Thanks again!!!

**Comment by seeholza** [comment]
> so if I want to test the triplets using the Quadruplet protocol, I just have to modify the stimulating time which will contsist of 60 quadruplets? 

Yes, to test this model with a quadruplet protocol you would have to set up spike times or pre- and postsynaptic neurons. You can do something like I did in the test for the [triplet_synapse](https://github.com/nest/nest-simulator/blob/master/pynest/nest/tests/test_stdp_triplet_synapse.py#L238) Lines 238-240, where you add another spike time of the post neuron, which would give pre-post-pre-post. And analogously for post-pre-post-pre.

> And another question,according to the aiticle if I want to see the LTP,there wii be two post and one pre? or see the LTD, there will be two pre and one post? Thanks again!!!

Yes, kind of. Basically, post-pre-post will lead to LTP (see the scholarpedia figure) and pre-post-pre will lead to LTD. This however, always depends on the parameters used in the model, the pairing frequency, as well as the times between spikes in the pair.

**Comment by seeholza** [comment]
@zifeo plese close this issue, since I believe all questions have been addressed. Please feel free to ask more, I will re-open!

**Comment by xiaoxiaoluzl** [comment]
OK ！ Thank you very much!

**Comment by xiaoxiaoluzl** [comment]
Hi
I have asked you some questions before ,and I'm very grateful for your answers. Now ，I have some new problems. So ,if I want to use the synapse of stdp_triplet_all_in_one_synapse to build a circuit， just like the
fig.1 in http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6673236, how can I control the ports of the post(n) and the post(n-1) or pre(n）and pre（n-1),if they comes from the same neuron. Namely, according to the circuit, if the postsynaptic neuron generates two spikes at different times , the ports of post(n） and post(n-1) will both feel the two spikes,thus making the corresponding transistors work twice.
However ,we just want these trasistors working once at correct time. So how I solve such problem.
At last , thanks again, and best wishes for you.
